apiVersion: apps/v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db_host: {{ .Values.secret.db_host }}
  db_user: {{ .Values.secret.db_user }}
  db_password: {{ .Values.secret.db_password }}