replicaCount: 2

image:
  repository: "anudeepbm1993/flywheel-java-app"
  tag: latest
  pullsecret: regcred

service:
  port: 80
  containerPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi" 

livenessProbe:
  path: /health
  port: 8080
readinessProbe:
  path: /health
  port: 8080

secretName: db-secret

secret:
  db_host: "<rds-endpoint>"
  db_user: "<db-username>"
  db_password: "<db-password>"

ingress:
  scheme: internet-facing
  targetType: ip
  listenPorts: '[{"HTTP": 80}]'
  class: alb
  path: /

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75