---
# Source: java-health-check-app/templates/secret.yaml
apiVersion: apps/v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
stringData:
  db_host: <rds-endpoint>
  db_user: <db-username>
  db_password: <db-password>
---
# Source: java-health-check-app/templates/service.yaml
apiVersion: apps/v1
kind: Service
metadata:
  name: java-health-check-java-health-check-app-svc
  namespace: default
spec:
  selector:
    app: java-health-check-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
# Source: java-health-check-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-health-check-java-health-check-app
  namespace: default
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: java-health-check-app
      template:
        metadata:
          labels:
            app: java-health-check-app
          spec:
            containers:
            - name: java-app
              image: "anudeepbm1993/flywheel-java-app:latest"
              ports:
              - containerPort: 8080
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                allowPrivilegeEscalation: false
              env:
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: db_host
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: db_port
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: db_user
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: db_password
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 10
                periodSeconds: 5
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 10
                periodSeconds: 5
            imagePullSecrets:
            - name: regcred
---
# Source: java-health-check-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-health-check-java-health-check-app-ingress
  namespace: default
  annotations:
    "alb.ingress.kubernetes.io/scheme": "internet-facing"
    "alb.ingress.kubernetes.io/target-type": "ip"
    "alb.ingress.kubernetes.io/listen-ports": '[{"HTTP": 80}]'
    "kubernetes.io/ingress.class": "alb"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-health-check-java-health-check-app-svc
                port:
                  number: 80
